# Generated by Django 3.0.5 on 2020-04-07 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Identifies the activity.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Describes the activity.')),
                ('frequency', models.PositiveIntegerField(help_text='Ideal maximum frequency of the activity in days. If the days since the activity is last performed exceeds the frequency, an alert may be provided.')),
                ('user', models.ForeignKey(help_text='The user this activity belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity', models.ForeignKey(help_text='The activity the event is for', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.Activity')),
            ],
        ),
    ]
