# Generated by Django 3.0.5 on 2020-04-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'activities'},
        ),
        migrations.AddField(
            model_name='activityevent',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Completed'), (2, 'Skipped')], default=1, help_text='The type of event'),
        ),
    ]
