# Generated by Django 3.0.5 on 2020-04-07 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20200407_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityevent',
            name='date',
        ),
        migrations.AddField(
            model_name='activityevent',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time of the event.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(help_text='The user this activity belongs to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='activity',
            field=models.ForeignKey(help_text='The activity the event is for.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.Activity'),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Completed'), (2, 'Skipped')], default=1, help_text='The type of event.'),
        ),
    ]
