# Generated by Django 3.0.5 on 2020-04-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200407_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Completed'), (2, 'Skipped'), (3, 'Created')], default=1, help_text='The type of event.'),
        ),
    ]
