# Generated by Django 3.0.5 on 2020-04-07 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200407_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('pk',), 'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelOptions(
            name='activityevent',
            options={'ordering': ('date_time',)},
        ),
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When the activity is created.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Completed'), (2, 'Skipped')], default=1, help_text='The type of event.'),
        ),
    ]
