# Generated by Django 3.0.5 on 2020-04-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200407_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'activities'},
        ),
    ]
