# Generated by Django 3.0.5 on 2020-04-09 13:42

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the colour', max_length=200)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', help_text='Name of the colour', max_length=18)),
            ],
        ),
    ]
