# Generated by Django 3.0.5 on 2020-04-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='hex_code',
        ),
    ]
