# Generated by Django 3.0.5 on 2020-04-09 09:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Identifies the activity.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Describes the activity.')),
                ('frequency', models.PositiveIntegerField(help_text='Ideal maximum frequency of the activity in days. If the days since the activity is last performed exceeds the frequency, an alert may be provided.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='frequency (in days)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the activity is created.')),
                ('user', models.ForeignKey(help_text='The user this activity belongs to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='The date of the event.')),
                ('event_type', models.PositiveSmallIntegerField(choices=[(1, 'Completed'), (2, 'Skipped')], default=1, help_text='The type of event.')),
                ('activity', models.ForeignKey(help_text='The activity the event is for.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='days_since.Activity')),
            ],
            options={
                'ordering': ('-date',),
                'unique_together': {('activity', 'date')},
            },
        ),
    ]
