# Generated by Django 3.0.5 on 2020-06-14 03:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days_since', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='frequency',
            field=models.PositiveIntegerField(help_text='Ideal maximum frequency of the activity in days. If the days since the activity is last performed exceeds the frequency, an alert may be provided.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='frequency (in days)'),
        ),
    ]
