# Generated by Django 3.0.5 on 2020-04-09 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '__first__'),
        ('days_since', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='color',
            field=models.ForeignKey(default=1, help_text='Colour attached to the activity', on_delete=django.db.models.deletion.PROTECT, to='web.Color'),
        ),
    ]
