# Generated by Django 3.0.7 on 2020-07-14 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200714_1800'),
        ('days_since', '0002_auto_20200614_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='color',
            field=models.ForeignKey(help_text='Colour attached to the activity.', on_delete=django.db.models.deletion.PROTECT, to='common.Color'),
        ),
    ]
