# Generated by Django 3.0.5 on 2020-04-09 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
        ('days_since', '0002_activity_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='color',
            field=models.ForeignKey(help_text='Colour attached to the activity', on_delete=django.db.models.deletion.PROTECT, to='web.Color'),
        ),
    ]
